#!/usr/bin/env bash
#
# ci_pre_xcodebuild.sh — Xcode Cloud pre-build hook.
#
# Runs automatically before every `xcodebuild archive` in Xcode Cloud.
# Xcode Cloud discovers this script by name at:
#   <repo root>/ci_scripts/ci_pre_xcodebuild.sh
# (path is hard-coded by Apple; don't rename or move it).
#
# What it does
# ------------
# Generates `ios/VoiceFlow/Secrets.swift` from the
# `ANTHROPIC_API_KEY` environment variable so the build has a real
# key without committing secrets to git. The file is gitignored on
# disk; Xcode Cloud runs this hook on a fresh clone every build, so
# it never has to persist.
#
# One-time setup on your side
# ---------------------------
# 1. App Store Connect → your app → Xcode Cloud tab → Manage
#    Workflows → click the workflow → Environment.
# 2. Click "+" next to Environment Variables.
# 3. Name: ANTHROPIC_API_KEY
#    Value: sk-ant-api03-...   (your real Anthropic key)
#    [x] Secret
# 4. Save.
# 5. Start a new build. This script picks up the env var, writes
#    Secrets.swift, then xcodebuild proceeds.
#
# Nothing to run locally. This script only executes inside Xcode
# Cloud's build environment.
#

set -euo pipefail

echo "==> ci_pre_xcodebuild.sh running"

# Xcode Cloud exposes CI_PRIMARY_REPOSITORY_PATH as the clone root.
# It's equivalent to $CI_WORKSPACE/repository. Fall back to pwd if
# that variable somehow isn't set (older Xcode Cloud images).
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(pwd)}"
SECRETS_PATH="$REPO_ROOT/ios/VoiceFlow/Secrets.swift"

if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
    echo "error: ANTHROPIC_API_KEY environment variable is not set." >&2
    echo "" >&2
    echo "To fix:" >&2
    echo "  1. App Store Connect → your app → Xcode Cloud → Manage Workflows" >&2
    echo "  2. Click the workflow → Environment → + (add variable)" >&2
    echo "  3. Name: ANTHROPIC_API_KEY  Value: sk-ant-...  [x] Secret" >&2
    echo "  4. Save and re-run the build." >&2
    exit 1
fi

# Escape backslashes and double-quotes so the Swift string literal
# can never be broken by a weird character in the key.
KEY_ESCAPED=$(printf '%s' "$ANTHROPIC_API_KEY" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

mkdir -p "$(dirname "$SECRETS_PATH")"
cat > "$SECRETS_PATH" <<EOF
//
//  Secrets.swift
//  VoiceFlow
//
//  Autogenerated by ci_scripts/ci_pre_xcodebuild.sh in Xcode Cloud.
//  Do not edit by hand — any changes will be overwritten on the next
//  build. This file is gitignored.
//

import Foundation

enum Secrets {
    static let anthropicAPIKey = "$KEY_ESCAPED"
}
EOF

echo "==> wrote $SECRETS_PATH"
ls -la "$SECRETS_PATH"
