#!/usr/bin/env bash
#
# generate-secrets.sh
#
# Writes ios/VoiceFlow/Secrets.swift from $ANTHROPIC_API_KEY so the
# build has an API key without committing one to the repo.
#
# Reads the key from (in order):
#   1. $ANTHROPIC_API_KEY environment variable
#   2. ~/.voiceflow.env  (a single line: ANTHROPIC_API_KEY=sk-ant-...)
#   3. A prompt if run interactively
#
# Safe to run repeatedly. Does nothing if Secrets.swift already exists
# with a non-placeholder key, unless $FORCE_REGEN=1.
#

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS_PATH="$REPO_ROOT/ios/VoiceFlow/Secrets.swift"

# 1. Try env var.
KEY="${ANTHROPIC_API_KEY:-}"

# 2. Try ~/.voiceflow.env
if [[ -z "$KEY" && -f "$HOME/.voiceflow.env" ]]; then
    # shellcheck disable=SC1090
    source "$HOME/.voiceflow.env"
    KEY="${ANTHROPIC_API_KEY:-}"
fi

# 3. Prompt interactively.
if [[ -z "$KEY" ]]; then
    if [[ -t 0 ]]; then
        read -r -s -p "Anthropic API key (hidden): " KEY
        echo
    else
        echo "error: ANTHROPIC_API_KEY not set and stdin is not a TTY." >&2
        echo "       Set the env var, create ~/.voiceflow.env, or run interactively." >&2
        exit 1
    fi
fi

if [[ -z "$KEY" ]]; then
    echo "error: no API key provided." >&2
    exit 1
fi

# Escape backslashes and double-quotes so the Swift string literal
# can't break if the key ever contains them. Anthropic keys don't,
# but be defensive.
KEY_ESCAPED=$(printf '%s' "$KEY" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

# If the file already exists with the same key and we're not forcing
# a regen, leave it alone. This keeps Xcode indexer happy on noop
# rebuilds.
if [[ -f "$SECRETS_PATH" && "${FORCE_REGEN:-0}" != "1" ]]; then
    if grep -q "\"$KEY_ESCAPED\"" "$SECRETS_PATH"; then
        echo "Secrets.swift already up to date."
        exit 0
    fi
fi

mkdir -p "$(dirname "$SECRETS_PATH")"
cat > "$SECRETS_PATH" <<EOF
//
//  Secrets.swift
//  VoiceFlow
//
//  AUTOGENERATED by Scripts/generate-secrets.sh. Do not edit by hand
//  — any changes will be overwritten on next build. This file is
//  gitignored.
//

import Foundation

enum Secrets {
    static let anthropicAPIKey = "$KEY_ESCAPED"
}
EOF

chmod 600 "$SECRETS_PATH"
echo "wrote $SECRETS_PATH"
